ERROR - 2024-10-02 03:23:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'marcaje', 3306, '', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#13 {main}
CRITICAL - 2024-10-02 03:23:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: POST, Route: auth/login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` IS NULL
 LIMIT 1', [], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/rewrite.php(44): require_once('/Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php')
ERROR - 2024-10-02 03:24:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'marcaje', 3306, '', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->login()
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#13 {main}
CRITICAL - 2024-10-02 03:24:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: POST, Route: auth/login]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` IS NULL
 LIMIT 1', [], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthController.php(55): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->login()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH/rewrite.php(44): require_once('/Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php')
ERROR - 2024-10-02 03:24:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'marcaje', 3306, '', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/StrictRules/Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('john@example.co...', 'email', Array, NULL, 'email')
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/Validation.php(204): CodeIgniter\Validation\Validation->processRules('email', 'email', 'john@example.co...', Array, Array, 'email')
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Controller.php(137): CodeIgniter\Validation\Validation->run()
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(22): CodeIgniter\Controller->validate(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->register()
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/StrictRules/Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('john@example.co...', 'email', Array, NULL, 'email')
#5 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Validation/Validation.php(204): CodeIgniter\Validation\Validation->processRules('email', 'email', 'john@example.co...', Array, Array, 'email')
#6 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Controller.php(137): CodeIgniter\Validation\Validation->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/citemplate/app/Controllers/AuthController.php(22): CodeIgniter\Controller->validate(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(933): App\Controllers\AuthController->register()
#9 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 /Applications/XAMPP/xamppfiles/htdocs/citemplate/system/rewrite.php(44): require_once('/Applications/X...')
#15 {main}
CRITICAL - 2024-10-02 03:24:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: POST, Route: auth/register]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Validation/StrictRules/Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/Validation/Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('john@example.com', 'email', [...], null, 'email')
 5 SYSTEMPATH/Validation/Validation.php(204): CodeIgniter\Validation\Validation->processRules('email', 'email', 'john@example.com', [...], [...], 'email')
 6 SYSTEMPATH/Controller.php(137): CodeIgniter\Validation\Validation->run()
 7 APPPATH/Controllers/AuthController.php(22): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthController->register()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH/rewrite.php(44): require_once('/Applications/XAMPP/xamppfiles/htdocs/citemplate/public/index.php')
